name: smart_parking_locator
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.0
  geolocator: ^9.0.2
  http: ^1.2.1
  provider: ^6.0.5
  flutter_polyline_points: ^2.1.0
  flutter_local_notifications: ^18.0.1
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.6
  uuid: ^3.0.6
  sqflite: ^2.0.0
  path_provider: ^2.0.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  flutter_map_tile_caching: ^9.1.3
  connectivity_plus: ^6.1.0
  latlong2: ^0.9.1
  isar: ^3.1.0+1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env